"""
Security and network policy models.

This module defines policy structures for firewall rules, segmentation,
device policies, and automation rules used throughout the Sentinel platform.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Optional, Any
from pydantic import BaseModel, Field
from uuid import UUID, uuid4


def _utc_now() -> datetime:
    """Get current UTC time (timezone-aware)."""
    return datetime.now(timezone.utc)


class PolicyAction(str, Enum):
    """Actions that can be taken by policies."""

    ALLOW = "allow"
    DENY = "deny"
    LOG = "log"
    ALERT = "alert"
    QUARANTINE = "quarantine"
    RATE_LIMIT = "rate_limit"


class PolicyScope(str, Enum):
    """Scope at which a policy applies."""

    GLOBAL = "global"
    VLAN = "vlan"
    DEVICE_GROUP = "device_group"
    DEVICE = "device"


class PolicyPriority(int, Enum):
    """Standard priority levels for policies."""

    CRITICAL = 10
    HIGH = 25
    NORMAL = 50
    LOW = 75
    DEFAULT = 100


class FirewallRule(BaseModel):
    """
    Individual firewall rule definition.

    Follows standard 5-tuple matching with zone-based extensions.

    Attributes:
        id: Unique rule identifier
        name: Human-readable rule name
        description: Rule description
        source_zones: Source security zones
        source_addresses: Source IP addresses or CIDRs
        source_ports: Source port ranges
        destination_zones: Destination security zones
        destination_addresses: Destination IP addresses or CIDRs
        destination_ports: Destination port ranges
        protocols: Protocols to match
        applications: Application signatures to match
        action: Action to take on match
        log_enabled: Whether to log matches
        priority: Rule priority (lower = higher priority)
        enabled: Whether rule is active
        auto_generated: Whether generated by an agent
        generated_by_agent: Name of generating agent
        created_at: Creation timestamp
        expires_at: Optional expiration timestamp
    """

    id: UUID = Field(default_factory=uuid4)
    name: str
    description: Optional[str] = None

    # Source
    source_zones: list[str] = Field(default_factory=list)
    source_addresses: list[str] = Field(default_factory=list)  # CIDR or IP
    source_ports: list[str] = Field(default_factory=list)

    # Destination
    destination_zones: list[str] = Field(default_factory=list)
    destination_addresses: list[str] = Field(default_factory=list)
    destination_ports: list[str] = Field(default_factory=list)

    # Match
    protocols: list[str] = Field(default_factory=lambda: ["any"])
    applications: list[str] = Field(default_factory=list)

    # Action
    action: PolicyAction = PolicyAction.DENY
    log_enabled: bool = False

    # Metadata
    priority: int = 100
    enabled: bool = True
    auto_generated: bool = False
    generated_by_agent: Optional[str] = None

    created_at: datetime = Field(default_factory=_utc_now)
    expires_at: Optional[datetime] = None

    @property
    def is_expired(self) -> bool:
        """Check if rule has expired."""
        if self.expires_at is None:
            return False
        return _utc_now() > self.expires_at

    def matches(
        self, src_ip: str, src_port: int, dst_ip: str, dst_port: int, protocol: str
    ) -> bool:
        """Check if traffic matches this rule."""
        # Simplified matching - real implementation would be more complex
        if self.protocols and "any" not in self.protocols:
            if protocol.lower() not in [p.lower() for p in self.protocols]:
                return False

        if self.source_addresses:
            # Would need CIDR matching here
            pass

        if self.destination_addresses:
            # Would need CIDR matching here
            pass

        if self.destination_ports:
            if str(dst_port) not in self.destination_ports:
                return False

        return True


class SegmentationPolicy(BaseModel):
    """
    Defines allowed communication between network segments.

    Used by Planner agent to auto-generate firewall rules.

    Attributes:
        id: Policy identifier
        name: Policy name
        description: Human-readable description
        source_vlan: Source VLAN ID
        destination_vlan: Destination VLAN ID
        allowed_services: Services explicitly allowed
        denied_services: Services explicitly denied
        default_action: Action for unlisted services
        enabled: Whether policy is active
    """

    id: UUID = Field(default_factory=uuid4)
    name: str
    description: Optional[str] = None

    source_vlan: int
    destination_vlan: int

    allowed_services: list[str] = Field(default_factory=list)
    denied_services: list[str] = Field(default_factory=list)

    # Default action if service not explicitly listed
    default_action: PolicyAction = PolicyAction.DENY

    enabled: bool = True

    def is_service_allowed(self, service: str) -> bool:
        """Check if a service is allowed by this policy."""
        if service in self.denied_services:
            return False
        if service in self.allowed_services:
            return True
        return self.default_action == PolicyAction.ALLOW


class DevicePolicy(BaseModel):
    """
    Policy applied to devices based on classification.

    Used for automatic device onboarding and segmentation.

    Attributes:
        id: Policy identifier
        name: Policy name
        match_device_types: Device types this policy matches
        match_vendors: Vendor names to match
        match_tags: Tags to match
        assign_vlan: VLAN to assign matching devices
        assign_zone: Security zone to assign
        assign_trust_level: Trust level to assign
        internet_access: Whether to allow internet access
        lan_access: Whether to allow LAN access
        allowed_destinations: Explicitly allowed destinations
        blocked_destinations: Explicitly blocked destinations
        qos_policy_id: QoS policy to apply
        priority: Policy priority
        enabled: Whether policy is active
    """

    id: UUID = Field(default_factory=uuid4)
    name: str

    # Matching
    match_device_types: list[str] = Field(default_factory=list)
    match_vendors: list[str] = Field(default_factory=list)
    match_tags: list[str] = Field(default_factory=list)

    # Assignment
    assign_vlan: Optional[int] = None
    assign_zone: Optional[str] = None
    assign_trust_level: Optional[str] = None

    # Restrictions
    internet_access: bool = True
    lan_access: bool = True
    allowed_destinations: list[str] = Field(default_factory=list)
    blocked_destinations: list[str] = Field(default_factory=list)

    # QoS
    qos_policy_id: Optional[UUID] = None

    priority: int = 100
    enabled: bool = True

    def matches_device(
        self, device_type: str, vendor: Optional[str] = None, tags: list[str] = None
    ) -> bool:
        """Check if a device matches this policy."""
        tags = tags or []

        if self.match_device_types:
            if device_type not in self.match_device_types:
                return False

        if self.match_vendors and vendor:
            if not any(v.lower() in vendor.lower() for v in self.match_vendors):
                return False

        if self.match_tags:
            if not any(t in tags for t in self.match_tags):
                return False

        return True


class AutomationRule(BaseModel):
    """
    Rules for agent automation.

    Defines conditions and actions that agents can take automatically.

    Attributes:
        id: Rule identifier
        name: Rule name
        description: Human-readable description
        trigger_event: Event type that triggers this rule
        trigger_conditions: Additional conditions for triggering
        action_type: Type of action to take
        action_params: Parameters for the action
        requires_confirmation: Whether human approval is needed
        confidence_threshold: Minimum confidence to execute
        max_executions_per_hour: Rate limiting
        rollback_enabled: Whether action can be rolled back
        rollback_timeout_seconds: Time window for rollback
        enabled: Whether rule is active
        execution_count: Number of times executed
        last_executed: Last execution timestamp
        last_result: Result of last execution
    """

    id: UUID = Field(default_factory=uuid4)
    name: str
    description: Optional[str] = None

    # Trigger
    trigger_event: str  # Event type that triggers this rule
    trigger_conditions: dict = Field(default_factory=dict)  # Additional conditions

    # Action
    action_type: str  # What action to take
    action_params: dict = Field(default_factory=dict)

    # Constraints
    requires_confirmation: bool = False
    confidence_threshold: float = Field(ge=0.0, le=1.0, default=0.8)
    max_executions_per_hour: Optional[int] = None

    # Rollback
    rollback_enabled: bool = True
    rollback_timeout_seconds: int = 3600

    enabled: bool = True

    # Stats
    execution_count: int = 0
    last_executed: Optional[datetime] = None
    last_result: Optional[str] = None

    def can_execute(self, executions_this_hour: int) -> bool:
        """Check if rule can be executed based on rate limits."""
        if not self.enabled:
            return False

        if self.max_executions_per_hour:
            if executions_this_hour >= self.max_executions_per_hour:
                return False

        return True

    def record_execution(self, result: str) -> None:
        """Record an execution of this rule."""
        self.execution_count += 1
        self.last_executed = _utc_now()
        self.last_result = result


class SecurityZone(BaseModel):
    """
    Security zone definition for zone-based policies.

    Attributes:
        id: Zone identifier
        name: Zone name
        description: Human-readable description
        trust_level: Default trust level for zone
        vlans: VLANs belonging to this zone
        default_ingress_policy: Default policy for incoming traffic
        default_egress_policy: Default policy for outgoing traffic
    """

    id: UUID = Field(default_factory=uuid4)
    name: str
    description: Optional[str] = None
    trust_level: str = "unknown"
    vlans: list[int] = Field(default_factory=list)
    default_ingress_policy: PolicyAction = PolicyAction.DENY
    default_egress_policy: PolicyAction = PolicyAction.ALLOW


class PolicySet(BaseModel):
    """
    Collection of related policies.

    Provides organization and batch operations for policies.
    """

    id: UUID = Field(default_factory=uuid4)
    name: str
    description: Optional[str] = None

    firewall_rules: list[FirewallRule] = Field(default_factory=list)
    segmentation_policies: list[SegmentationPolicy] = Field(default_factory=list)
    device_policies: list[DevicePolicy] = Field(default_factory=list)
    automation_rules: list[AutomationRule] = Field(default_factory=list)
    zones: list[SecurityZone] = Field(default_factory=list)

    enabled: bool = True
    version: int = 1
    created_at: datetime = Field(default_factory=_utc_now)
    updated_at: datetime = Field(default_factory=_utc_now)

    def get_firewall_rules_sorted(self) -> list[FirewallRule]:
        """Get firewall rules sorted by priority."""
        return sorted([r for r in self.firewall_rules if r.enabled], key=lambda r: r.priority)
